apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hospital-management
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/emmanuelokpatuma/hospitalmanagement
    targetRevision: main
    path: hpm
    helm:
      valueFiles:
      - values-ui.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: hospital
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
