---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hospital-management
  namespace: argocd
spec:
  description: Hospital Management Multi-Service Application
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
