{{- if .Values.sqlserver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hpm.fullname" . }}-sqlserver
  labels:
    {{- include "hpm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hpm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hpm.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: 10001
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "YourStrong!Passw0rd"
        - name: MSSQL_PID
          value: "Express"
        volumeMounts:
        - name: sqlserver-data
          mountPath: /var/opt/mssql
      volumes:
      - name: sqlserver-data
        persistentVolumeClaim:
          claimName: {{ include "hpm.fullname" . }}-sqlserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hpm.fullname" . }}-sqlserver
  labels:
    {{- include "hpm.labels" . | nindent 4 }}
spec:
  ports:
  - port: 1433
    targetPort: 1433
  selector:
    {{- include "hpm.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hpm.fullname" . }}-sqlserver-pvc
  labels:
    {{- include "hpm.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
{{- end }}